[package]
name = "audiorouter-cli"
version = "0.0.11"
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
audiorouter-control = { path = "../control" }
audiorouter-domain = { path = "../domain" }
audiorouter-storage = { path = "../storage" }
audiorouter-recording = { path = "../recording" }
audiorouter-protocol = { path = "../protocol" }
audiorouter-transport = { path = "../transport" }
serde_json = { workspace = true }
